---


- name: Add User
  user: 
    name={{ item.name }} 
    home={{ item.home }} 
    shell={{ item.shell }} 
    groups=users,wheel 
    generate_ssh_key=yes 
    ssh_key_bits=2048
  with_items: '{{ system_users }}'
  become: yes
  tags:
    - adduser

- name: sudo without password for wheel group
  copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/wheel_nopasswd
    mode: 0440
  become: yes
  tags:
    - addsudo

- name: set password
  shell: echo yo:banik | sudo chpasswd

- name: Add authorized keys
  authorized_key: user={{ item.name }} key="{{ lookup("file", item.key2) }}"
  with_items: '{{ system_users }}'
  become: yes
  tags:
    - addkeys
